apps/tour/urls.py
from django.urls import path

from apps.event.views import EventListView, EventDetailView, EventCreateView

app_name = 'apps.tour'

urlpatterns = [
    path('', EventListView.as_view(), name='tour_list'),
    path('<int:pk>/', EventDetailView.as_view(), name='tour_detail'),
    path('create/', EventCreateView.as_view(), name='tour_create'),
]

apps/urls.py
from rest_framework_simplejwt import views as jwt_views
from rest_framework.routers import DefaultRouter

from django.urls import path, include

from apps.core.api.views import RegionModelViewSet, DistrictModelViewSet, \
    NeighborhoodModelViewSet
from apps.core.views.user import MeUserView

router = DefaultRouter()
router.register('regions', RegionModelViewSet, 'regions')
router.register('districts', DistrictModelViewSet, 'districts')
router.register('neighborhoods', NeighborhoodModelViewSet, 'neighborhoods')

urlpatterns = [
    path('core/', include(router.urls)),
    path('auth/me/', MeUserView.as_view(), name='me'),
    path('auth/token/', jwt_views.TokenObtainPairView.as_view(),
         name='token_obtain_pair'),
    path('auth/token/refresh/', jwt_views.TokenRefreshView.as_view(),
         name='token_refresh'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

from apps.core.views.views import MainPageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', MainPageView.as_view(), name='home'),
    path('hotels/', include('apps.hotel.urls', namespace='apps.hotel')),
    path('events/', include('apps.event.urls', namespace='apps.event')),
    path('tours/', include('apps.tour.urls', namespace='apps.tour')),

    path('manifest.json',
         TemplateView.as_view(template_name='manifest.json', content_type='application/json')),
    url(r'^select2/', include('django_select2.urls')),
    # telegram bot handler
    url(r'^', include('django_telegrambot.urls')),
    path('api/v1/', include('apps.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/event/models.py
from django.contrib.gis.db import models
from django.utils import timezone
from apps.core.models import BaseModel


class EventManager(models.Manager):
    def get_queryset(self):
        now = timezone.localtime(timezone.now())
        return super().get_queryset().filter(confirmed=True, end_date__gte=now)


class Event(BaseModel):
    name = models.CharField(max_length=255)
    text = models.TextField()
    address = models.CharField(max_length=255, blank=True)
    image = models.ImageField(upload_to='events/', blank=True)
    certificate = models.FileField(upload_to='events-certificate/', blank=True)
    phone = models.CharField(max_length=13, blank=True)
    email = models.EmailField(max_length=255, blank=True)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    geo_position = models.PointField()
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    neighborhood = models.ManyToManyField('core.Neighborhood',
                                          related_name='event')
    source_url = models.URLField(blank=True)
    confirmed = models.BooleanField(default=False)

    event_category = models.ManyToManyField('event.EventCategory',
                                            related_name='event_category')

    objects = models.Manager()
    raw_objects = EventManager()

    class Meta:
        verbose_name = 'Tadbir'
        verbose_name_plural = 'Tadbirlar'
        ordering = ['-id']

    def __str__(self):
        return self.name


class EventCategory(BaseModel):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

apps/tour/models/models.py
from django.contrib.gis.db import models
from apps.core.models import BaseModel


class TourObjects(BaseModel):
    name = models.CharField(max_length=128)
    phone = models.CharField(max_length=13)
    email = models.EmailField()
    link = models.TextField()
    geo_position = models.PointField()
    description = models.TextField()
    category = models.ForeignKey('core.Category', on_delete=models.CASCADE)
    specializations = models.ManyToManyField('core.Specializations', blank=True)
    services = models.ManyToManyField('core.Services', blank=True)
    certificates = models.ManyToManyField('core.Certificates', blank=True)
    images = models.ManyToManyField('core.Images', blank=True)
    user = models.ForeignKey('core.User', null=True, on_delete=models.SET_NULL, blank=True)
    telegram = models.ForeignKey('telegram_bot.TelegramUsers', null=True, on_delete=models.SET_NULL)
    confirmed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-id', )


class Guide(BaseModel):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    middle_name = models.CharField(max_length=64)
    certificate_number = models.CharField(max_length=64)
    email = models.EmailField()
    phone = models.CharField(max_length=13)
    district = models.ManyToManyField('core.District', blank=True)
    languages = models.ManyToManyField('core.Language', blank=True)
    avatar = models.FileField(blank=True, null=True, upload_to='guide/')
    user = models.ForeignKey('core.User', null=True, on_delete=models.SET_NULL)
    telegram = models.ForeignKey('telegram_bot.TelegramUsers', null=True, on_delete=models.SET_NULL, blank=True)
    confirmed = models.BooleanField(default=False)

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

    class Meta:
        ordering = ('-id',)


class Transport(BaseModel):
    DRIVER = 'DRIVER'
    PASSENGER = 'PASSENGER'
    ROLE = (
        (DRIVER, 'Driver'),
        (PASSENGER, 'Passenger')
    )

    automobile = models.CharField(max_length=64)
    role = models.CharField(max_length=32, choices=ROLE)
    phone = models.CharField(max_length=32)
    from_direction = models.ManyToManyField('core.Region', related_name='from_direction', blank=True)
    to_direction = models.ManyToManyField('core.Region', related_name='to_direction', blank=True)
    user = models.ForeignKey('core.User', null=True, on_delete=models.SET_NULL, blank=True)
    telegram = models.ForeignKey('telegram_bot.TelegramUsers', null=True, on_delete=models.SET_NULL, blank=True)
    confirmed = models.BooleanField(default=False)

    def __str__(self):
        return "%s -> %s" % (self.from_direction.name, self.to_direction.name)

    class Meta:
        ordering = ('-id',)

apps/tour/views/views.py
from django.shortcuts import render

# Create your views here.

templates/pages/tours/destination.html
{% extends 'site_base.html' %}

{% load static %}

{% block extrahead %}
{% endblock %}

{% block page_content %}
  {{ block.super }}
  <section class="content">
    <div class="site-blocks-cover inner-page-cover" style="background-image: url({% static 'assets/images/hero_bg_2.jpg' %});" data-aos="fade" data-stellar-background-ratio="0.5">
        <div class="container">
          <div class="row align-items-center justify-content-center text-center">

            <div class="col-md-8" data-aos="fade-up" data-aos-delay="400">
              <h1 class="text-white font-weight-light">Destinations</h1>
              <div><a href="index.html">Home</a> <span class="mx-2 text-white">&bullet;</span> <span class="text-white">Destinations</span></div>

            </div>
          </div>
        </div>
      </div>

    <div class="site-section">

      <div class="container">

        <div class="row">
          <div class="col-md-6 col-lg-4 mb-4 mb-lg-4">
            <a href="#" class="unit-1 text-center">
              <img src="{% static 'assets/images/01-greece.jpg' %}" alt="Image" class="img-fluid">
              <div class="unit-1-text">
                <strong class="text-primary mb-2 d-block">$590</strong>
                <h3 class="unit-1-heading">Santorini, Greece</h3>
              </div>
            </a>
          </div>
          <div class="col-md-6 col-lg-4 mb-4 mb-lg-4">
            <a href="#" class="unit-1 text-center">
              <img src="{% static 'assets/images/02-rome.jpg' %}" alt="Image" class="img-fluid">
              <div class="unit-1-text">
                <strong class="text-primary mb-2 d-block">$390</strong>
                <h3 class="unit-1-heading">Rome, Italy</h3>
              </div>
            </a>
          </div>
          <div class="col-md-6 col-lg-4 mb-4 mb-lg-4">
            <a href="#" class="unit-1 text-center">
              <img src="{% static 'assets/images/03-japan.jpg' %}" alt="Image" class="img-fluid">
              <div class="unit-1-text">
                <strong class="text-primary mb-2 d-block">$390</strong>
                <h3 class="unit-1-heading">Mount Fuji, Japan</h3>
              </div>
            </a>
          </div>

          <div class="col-md-6 col-lg-4 mb-4 mb-lg-4">
            <a href="#" class="unit-1 text-center">
              <img src="{% static 'assets/images/04-dubai.jpg' %}" alt="Image" class="img-fluid">
              <div class="unit-1-text">
                <strong class="text-primary mb-2 d-block">$320</strong>
                <h3 class="unit-1-heading">Camels, Dubai</h3>
              </div>
            </a>
          </div>
          <div class="col-md-6 col-lg-4 mb-4 mb-lg-4">
            <a href="#" class="unit-1 text-center">
              <img src="{% static 'assets/images/05-london.jpg' %}" alt="Image" class="img-fluid">
              <div class="unit-1-text">
                <strong class="text-primary mb-2 d-block">$290</strong>
                <h3 class="unit-1-heading">Elizabeth Tower, London</h3>
              </div>
            </a>
          </div>
          <div class="col-md-6 col-lg-4 mb-4 mb-lg-4">
            <a href="#" class="unit-1 text-center">
              <img src="{% static 'assets/images/06-australia.jpg' %}" alt="Image" class="img-fluid">
              <div class="unit-1-text">
                <strong class="text-primary mb-2 d-block">$390</strong>
                <h3 class="unit-1-heading">Opera House, Australia</h3>
              </div>
            </a>
          </div>
        </div>
      </div>

    </div>

    <div class="site-section block-13 bg-light">


    <div class="container">
        <div class="row justify-content-center mb-5">
          <div class="col-md-7">
            <h2 class="font-weight-light text-black text-center">What People Says</h2>
          </div>
        </div>

        <div class="nonloop-block-13 owl-carousel">

          <div class="item">
            <div class="container">
              <div class="row">
                <div class="col-lg-6 mb-5">
                  <img src="{% static 'assets/images/img_1.jpg' %}" alt="Image" class="img-md-fluid">
                </div>
                <div class="overlap-left col-lg-6 bg-white p-md-5 align-self-center">
                  <p class="text-black lead">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique dolorem quisquam laudantium, incidunt id laborum, tempora aliquid labore minus. Nemo maxime, veniam! Fugiat odio nam eveniet ipsam atque, corrupti porro&rdquo;</p>
                  <p class="">&mdash; <em>James Martin</em>, <a href="#">Traveler</a></p>
                </div>
              </div>
            </div>
          </div>

          <div class="item">
            <div class="container">
              <div class="row">
                <div class="col-lg-6 mb-5">
                  <img src="{% static 'assets/images/img_2.jpg' %}" alt="Image" class="img-md-fluid">
                </div>
                <div class="overlap-left col-lg-6 bg-white p-md-5 align-self-center">
                  <p class="text-black lead">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique dolorem quisquam laudantium, incidunt id laborum, tempora aliquid labore minus. Nemo maxime, veniam! Fugiat odio nam eveniet ipsam atque, corrupti porro&rdquo;</p>
                  <p class="">&mdash; <em>Clair Augustin</em>, <a href="#">Traveler</a></p>
                </div>
              </div>
            </div>
          </div>

          <div class="item">
            <div class="container">
              <div class="row">
                <div class="col-lg-6 mb-5">
                  <img src="{% static 'assets/images/img_4.jpg' %}" alt="Image" class="img-md-fluid">
                </div>
                <div class="overlap-left col-lg-6 bg-white p-md-5 align-self-center">
                  <p class="text-black lead">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique dolorem quisquam laudantium, incidunt id laborum, tempora aliquid labore minus. Nemo maxime, veniam! Fugiat odio nam eveniet ipsam atque, corrupti porro&rdquo;</p>
                  <p class="">&mdash; <em>James Martin</em>, <a href="#">Traveler</a></p>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="site-section">
      <div class="container">
        <div class="row align-items-stretch">
          <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
            <div class="unit-4 d-flex">
              <div class="unit-4-icon mr-4"><span class="text-primary flaticon-airplane"></span></div>
              <div>
                <h3>Air Ticketing</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis quis molestiae vitae eligendi at.</p>
                <p><a href="#">Learn More</a></p>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
            <div class="unit-4 d-flex">
              <div class="unit-4-icon mr-4"><span class="text-primary flaticon-ship"></span></div>
              <div>
                <h3>Cruises</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis quis molestiae vitae eligendi at.</p>
                <p><a href="#">Learn More</a></p>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-4 mb-lg-0">
            <div class="unit-4 d-flex">
              <div class="unit-4-icon mr-4"><span class="text-primary flaticon-route"></span></div>
              <div>
                <h3>Tour Packages</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis quis molestiae vitae eligendi at.</p>
                <p><a href="#">Learn More</a></p>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </section>
{% endblock %}

{% block scripts %}
  {{ block.super }}
{% endblock %}

templates/pages/tours/tour_create.html
{% extends 'site_base.html' %}

{% load static %}

{% block extrahead %}
  {{ block.super }}
  {{ form.media.css }}
  <link rel="stylesheet" href="{% static 'assets/libs/jquery-datetimepicker/css/tempusdominus-bootstrap-4.min.css' %}" />
{% endblock %}

{% block page_content %}
  {{ block.super }}
  <section class="content">
    <div class="add-form">
      <div class="container">
        <form method="post">
          {% csrf_token %}
          <div class="messages">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    <strong>{{field.name}} {{ error|escape }}</strong>
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  <strong>{{ error|escape }}</strong>
                </div>
              {% endfor %}
            {% endif %}
          </div>
          <div class="form-group">
            <label>Kategoriyani tanlang</label>
            {{ form.event_category }}
          </div>
          <div class="form-group">
            <label>Nomi</label>
            {{ form.name }}
          </div>
          <div class="form-group">
            <label>Matn</label>
            {{ form.text }}
          </div>
          <div class="form-group">
            <label>Rasm</label>
            {{ form.image }}
          </div>
          <div class="form-group">
            <label>Email</label>
            {{ form.email }}
          </div>
        <div class="form-group">
            <label>Sertificat</label>
            {{ form.certificate }}
          </div>
          <div class="form-group">
            <label>Manba(sayt)</label>
            {{ form.source_url }}
          </div>
          <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                  <label>Boshlanish sanasi va vaqti</label>
                    <div class="input-group date" id="date-start" data-target-input="nearest">
                        <input type="text" class="form-control datetimepicker-input" data-target="#date-start"/>
                        <div class="input-group-append" data-target="#date-start" data-toggle="datetimepicker">
                            <div class="input-group-text"><span class="glyphicon icon-calendar"></span></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label>Tugash sanasi va vaqti</label>
                     <div class="input-group date" id="date-end" data-target-input="nearest">
                        <input type="text" class="form-control datetimepicker-input" data-target="#date-end"/>
                        <div class="input-group-append" data-target="#date-end" data-toggle="datetimepicker">
                            <div class="input-group-text"><span class="glyphicon icon-calendar"></span></div>
                        </div>
                    </div>
                </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label>Manzil</label>
                    {{ form.address }}
                </div>
            </div>
            <div class="col-md-12">
                <div><span>Xaritadagi joyni tanlang yoki koordinatalarni kiriting</span></div>
                <div id="map" class="map-container view-place-map-container" style="width: 100%; height: 300px;"></div>
                <div class="form-group">
                    <input name="latitude" type="hidden">
                </div>
                <div class="form-group">
                    <input name="longitude" type="hidden">
                </div>
            </div>
          </div>
          <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Qo'shish">
          </div>
        </form>
      </div>
    </div>
  </section>
{% endblock %}

{% block scripts %}
  {{ block.super }}
  {{ form.media.js }}
  <script type="text/javascript" src="{% static 'assets/libs/jquery-datetimepicker/js/moment.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'assets/libs/jquery-datetimepicker/js/tempusdominus-bootstrap-4.min.js' %}"></script>
  <script src="https://api-maps.yandex.ru/2.1/?apikey=08b75e37-75f6-485b-9c9b-b7246841358b&lang=ru_RU" type="text/javascript"></script>
{% endblock %}

{% block page_scripts %}
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script type="text/javascript">
      $(function () {
          $('#date-start').datetimepicker({
            format: 'YYYY-MM-DD HH:mm',
            locale: 'ru'
          });
          $('#date-end').datetimepicker({
            format: 'YYYY-MM-DD HH:mm'
          });
      });

    ymaps.ready(init);

    function init() {
        var lat = 41.335918;
        var lng = 64.424532;
        var myPlacemark = null;

        var myMap = new ymaps.Map("map", {
            center: [lat, lng],
            zoom: 5
        });

        // Слушаем клик на карте.
        myMap.events.add('click', function (e) {
            var coords = e.get('coords');

            $('input[name="longitude"]').val(coords[1]);
            $('input[name="latitude"]').val(coords[0]);

            // Если метка уже создана – просто передвигаем ее.
            if (myPlacemark) {
                myPlacemark.geometry.setCoordinates(coords);
            }
            // Если нет – создаем.
            else {
                myPlacemark = createPlacemark(coords);
                myMap.geoObjects.add(myPlacemark);
                // Слушаем событие окончания перетаскивания на метке.
                myPlacemark.events.add('dragend', function () {
                    getAddress(myPlacemark.geometry.getCoordinates());
                });
            }
            getAddress(coords);
        });

        // Создание метки.
        function createPlacemark(coords) {
            return new ymaps.Placemark(coords, {
                iconCaption: 'поиск...'
            }, {
                preset: 'islands#violetDotIconWithCaption',
                draggable: true
            });
        }

        // Определяем адрес по координатам (обратное геокодирование).
        function getAddress(coords) {
            myPlacemark.properties.set('iconCaption', 'поиск...');
            ymaps.geocode(coords).then(function (res) {
                var firstGeoObject = res.geoObjects.get(0);

                myPlacemark.properties
                    .set({
                        // Формируем строку с данными об объекте.
                        iconCaption: [
                            // Название населенного пункта или вышестоящее административно-территориальное образование.
                            firstGeoObject.getLocalities().length ? firstGeoObject.getLocalities() : firstGeoObject.getAdministrativeAreas(),
                            // Получаем путь до топонима, если метод вернул null, запрашиваем наименование здания.
                            firstGeoObject.getThoroughfare() || firstGeoObject.getPremise()
                        ].filter(Boolean).join(', '),
                        // В качестве контента балуна задаем строку с адресом объекта.
                        balloonContent: firstGeoObject.getAddressLine()
                    });
                $('#id_address').val(firstGeoObject.getAddressLine());
            });
        }
      }
  </script>
{% endblock %}

templates/pages/tours/tour_detail.html
{% extends 'site_base.html' %}

{% load static %}

{% block extrahead %}
    <link rel="stylesheet" href="{% static 'assets/libs/social-kit/css/social-share-kit.css' %}" />
{% endblock %}

{% block page_content %}
  <section class="content">
       <div class="event-detail">
           <div class="event-detail-bg" style="background-image: url({{ object.image.url }})">

           </div>
                <div class="event-detail-short">
                    <div class="container">
                        <p class="even-item-date"><span class="icon-calendar"></span> {{ object.start_date|date:"d M Y" }}</p>
                    <p class="even-item-map"><span class="icon-address-book"></span> {{object.address}}</p>
                    </div>
                </div>
               <div class="event-detail-content">
                    <div class="container">
                        <div class="event-description-title"> {{ object.name }} </div>
                        <div class="event-detail-inner">
                            <div class="event-detail-left">
                                <div class="event-description-text">
                                {{ object.text }}
                                </div>
                            </div>
                            <div class="event detail-right">
                                <div class="ssk-group">
                                    <a href="" class="ssk ssk-facebook"></a>
                                    <a href="" class="ssk ssk-twitter"></a>
                                    <a href="" class="ssk ssk-google-plus"></a>
                                    <a href="" class="ssk ssk-pinterest"></a>
                                    <a href="" class="ssk ssk-tumblr"></a>
                                </div>
                            </div>
                        </div>
                    </div>
               </div>
               <div class="event-detail-map">
                    <div id="map"></div>
                    <script>
                // Initialize and add the map
                function initMap() {
                  // The location of Uluru
                  var uluru = {lat: 41.5026497, lng: 62.1295331};
                  // The map, centered at Uluru
                  var map = new google.maps.Map(
                      document.getElementById('map'), {zoom: 6, center: uluru});
                  // The marker, positioned at Uluru
                  var marker = new google.maps.Marker({position: uluru, map: map});
                }
              </script>

               <script async defer
                       src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAwsx3hw-XCvOFwh-Q6QVTrI-7bhSkoO4M&callback=initMap">
               </script>
               </div>
       </div>
  </section>
{% endblock %}

{% block scripts %}
  {{ block.super }}
    <script type="text/javascript" src="{% static 'assets/libs/social-kit/js/social-share-kit.min.js' %}"></script>

    <script>
        SocialShareKit.init();
    </script>
{% endblock %}

templates/pages/tours/tours.html
{% extends 'site_base.html' %}

{% load static %}

{% block extrahead %}
    <link rel="stylesheet" href="{% static 'assets/libs/jquery-datetimepicker/css/tempusdominus-bootstrap-4.min.css' %}" />
{% endblock %}

{% block page_content %}
  {{ block.super }}
  <section class="content">
        <section class="events">
      <div class="container">
        <div class="event-filter-box">
        <div class="even-title">
          <h2 class="font-weight-light text-black">Tadbirlar</h2>
        </div>
        <div class="event-filter">
          <form>
              <div class="event-filter-input">
                <div class="form-group">
              <select class="form-control" name="event_category">
                <option>Ekskursiya</option>
                <option>Festival</option>
                <option>Konsert</option>
                <option>Sayl o'yin</option>
                <option>Kecha</option>
                <option>Ko'rgazma</option>
                <option>Seminar</option>
                <option>Konferensiya</option>
                <option>Forum</option>
                <option>Ko'ngil ochar</option>
                <option>Gastronomik</option>
              </select>
            </div>
              <div class="form-group">
                 <div class="input-group date" id="date" data-target-input="nearest">
                    <input type="text" class="form-control datetimepicker-input" data-target="#date" name="date"/>
                    <div class="input-group-append" data-target="#date" data-toggle="datetimepicker">
                        <div class="input-group-text"><span class="glyphicon icon-calendar"></span></div>
                    </div>
                </div>
              </div>
            <div class="form-group">
              <input type="text" name="location" placeholder="Location">
            </div>
            <div class="form-group">
              <select class="form-control" name="event_price">
                <option>Narx</option>
                <option>Hammasi</option>
                <option>Tekin</option>
                <option>Pulli</option>
              </select>
            </div>
              </div>
          </form>
        </div>
      </div>

          <div class="event-content">
              {% for object in object_list %}
              <div class="event-item">
                  <a href="{% url 'apps.event:event_detail' object.id %}">
                      {% if object.image %}
                      <div class="event-item-img" style=" background-image: url({{ object.image.url }})">
                      </div>
                      {% endif %}
                      <div class="event-item-text">
                          <h3 class="event-item-title">{{ object.name }} </h3>
                          <p class="even-item-date"><span class="icon-calendar"></span> {{ object.start_date }}</p>
                          <p class="even-item-map"><span class="icon-address-book"></span> {{ object.address }}</p>
                      </div>
                  </a>
              </div>
              {% endfor %}
          </div>
      </div>
    </section>
  </section>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'assets/libs/jquery-datetimepicker/js/moment.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/libs/jquery-datetimepicker/js/tempusdominus-bootstrap-4.min.js' %}"></script>
{% endblock %}


{% block page_scripts %}
    <script type="text/javascript">
      $(function () {
          $('#date').datetimepicker({
            format: 'YYYY-MM-DD',
          });
      });
  </script>
{% endblock %}